# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_contact_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('email_adress', models.CharField(max_length=200)),
                ('media_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverSide.Media_User')),
            ],
        ),
    ]
